apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress-sample-domain1-admin-server
  namespace: sample-domain1-ns
  labels:
    weblogic.domainUID: sample-domain1
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  routes:
  - kind: Rule
    match: PathPrefix(`/console`)
    services:
    - kind: Service
      name: sample-domain1-admin-server
      port: 7001