apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ${WEBLOGIC_DOMAIN_NAME}-admin-server
  namespace: ${SAMPLE_NS}
  labels:
    weblogic.domainUID: ${WEBLOGIC_DOMAIN_UID}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  routes:
  - kind: Rule
    match: PathPrefix(`/console`)
    services:
    - kind: Service
      name: "${WEBLOGIC_DOMAIN_NAME}-admin-server"
      port: 7001