apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ${WEBLOGIC_DOMAIN_NAME}
  namespace: ${SAMPLE_NS}
  labels:
    weblogic.domainUID: ${WEBLOGIC_DOMAIN_UID}
  annotations:
    kubernetes.io/ingress.class: traefik

spec:
  routes:
  - kind: Rule
    match: Host(`${WEBLOGIC_DOMAIN_NAME}.${SAMPLE_NS}.sample`)
    services:
    - kind: Service
      name: "${WEBLOGIC_DOMAIN_NAME}-cluster-${WEBLOGIC_CLUSTER_NAME}"
      port: 8001