apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress-sample-domain2-cluster-cluster-1
  namespace: sample-domain1-ns
  labels:
    weblogic.domainUID: sample-domain2
  annotations:
    kubernetes.io/ingress.class: traefik

spec:
  routes:
  - kind: Rule
    match: Host(`sample-domain2-cluster-cluster-1.sample.org`)
    services:
    - kind: Service
      name: sample-domain2-cluster-cluster-1
      port: 8001