apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: mysql-db
  labels:
    app: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-db
      app.kubernetes.io/instance: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql-db
        app.kubernetes.io/instance: dev
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql